[tool.black]
line-length = 99

[tool.deptry]
requirements_txt = ["src/requirements.txt"]

[tool.deptry.per_rule_ignores]
DEP003 = ["httpx"]

[tool.coverage.run]
source = ["src"]

[tool.isort]
include_trailing_comma = true
line_length = 99
multi_line_output = 3
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
install_types = true
non_interactive = true

[tool.pytest.ini_options]
addopts = "--cov --cov-append --cov-report=term-missing --cov-fail-under=25 -ra --show-capture=no --tb short"
python_files = ["*.py"]

[tool.ruff]
fix = false
ignore = ["S101"]
line-length = 99
select = ["A", "ARG", "B", "BLE", "C4", "C90", "D", "E", "F", "I", "ICN", "N", "PGH", "PLC", "PLE", "PLR", "PLW", "Q", "RET", "RUF", "S", "SIM", "T10", "T20", "TID", "UP", "W", "YTT"]

[tool.ruff.isort]
known-first-party = []

[tool.ruff.mccabe]
max-complexity = 12

[tool.ruff.per-file-ignores]
"tests/*" = ["ANN001", "ERA001", "S101", "S105", "S106"]
